---
title: "Symptom Beliefs"
output:
  html_document:
    df_print: paged
---

```{r}
library(easypackages)
libraries("tidyverse", "ggplot2", "scales", "knitr", "kableExtra", "lme4", "lmerTest", "rmcorr")

rm(list = ls())

df <- readRDS(file = "S:\\TRACK to TREAT\\Data\\Processed Data\\depression_belief_data.rds") %>%
  select(yb_lsmh_id:p3m_defOther)

symptoms <- c("Interest", "Down", "Sleep", "Energy", "Appetite", "Self", "Concentrate", "Pace", "Suicide", "Other")
```

## Sample Description

```{r}
count(df, pb_childethnicity_alt) %>%
  mutate(prop = n / sum(n))
count(df, pb_childgender) %>%
  mutate(prop = n / sum(n))
count(df, pb_childage) %>%
  mutate(prop = n / sum(n))
count(df, pb_income) %>%
  mutate(prop = n / sum(n))
```

## Analysis 1: Description of Symptom Beliefs

```{r}
table_1 <- df %>%
  select(matches("y.*_def")) %>%
  pivot_longer(everything()) %>%
  mutate(name = gsub("^.*_", "", name)) %>%
  group_by(name) %>%
  summarize(prop = mean(value, na.rm = T))

table_1
saveRDS(table_1, file = "S:\\TRACK to TREAT\\Data\\Processed Data\\Table 1.rds")
```

## Analysis 2: Child Belief Stability

Spearman correlation (cor)

```{r}
out_2 <- tibble()

for(x in symptoms) {
  
  baseline <- df[[paste0("yb_def", x)]]
  followUp <- df[[paste0("y3m_def", x)]]
  
  correlation <- cor.test(
    baseline,
    followUp,
    use = "complete.obs"
  )
  
  results <- tibble(
    x = x,
    agree = mean(baseline == followUp, na.rm = T),
    r = correlation$estimate,
    p = correlation$p.value
  )
  
  out_2 <- rbind(out_2, results)
  
}

# p-adjust
out_2$p <- p.adjust(out_2$p, "BH")

# Report
out_2 %>%
  arrange(p) %>%
  kable() %>%
  kable_styling()

mean(out_2$agree)
mean(out_2$r)
```

## Analysis 3: Child and Parent Belief Agreement

Repeated measures correlation (rmcorr)

```{r}
df_long_3_y <- df %>%
  select(yb_lsmh_id, paste0("yb_def", symptoms), paste0("y3m_def", symptoms)) %>%
  pivot_longer(-yb_lsmh_id, 
               names_sep = "_",
               names_to = c("time", ".value")) %>%
  mutate(time = gsub("y", "", time))

df_long_3_p <- df %>%
  select(yb_lsmh_id, paste0("pb_def", symptoms), paste0("p3m_def", symptoms)) %>%
  pivot_longer(-yb_lsmh_id, 
               names_sep = "_",
               names_to = c("time", ".value")) %>%
  mutate(time = gsub("p", "", time))

df_long_3 <- inner_join(df_long_3_y, df_long_3_p, 
                        by = c("yb_lsmh_id", "time"),
                        suffix = c("_youth", "_parent"))

out_3 <- tibble()

for(x in symptoms) {
  
  child <- paste0("def", x, "_youth")
  parent <- paste0("def", x, "_parent")
  
  correlation <- rmcorr(
    data = df_long_3,
    participant = "yb_lsmh_id",
    measure1 = child,
    measure2 = parent
  )
  
  results <- tibble(
    x = x,
    agree = mean(df_long_3[[child]] == df_long_3[[parent]], na.rm = T),
    r = correlation$r,
    p = correlation$p
  )
  
  out_3 <- rbind(out_3, results)
      
}

# p-adjust
out_3$p <- p.adjust(out_3$p, "BH")

# Report
out_3 %>%
  arrange(p) %>%
  kable() %>%
  kable_styling()

mean(out_3$agree)
mean(out_3$r, na.rm = T)
```
